<h1>Anmelden</h1>
<form id="login-form">
	<input type="email" name="email" placeholder="E-Mail-Adresse" required="true" id="email-field" class="mobile-full-width">
	<input type="password" name="password" placeholder="Passwort" required="true" id="password-field" class="mobile-full-width">
	<button type="submit" class="default mobile-full-width" id="login-button">Anmelden</button>
	<img src="app/client/view/resources/images/Loading.webp" id="loading-indicator" class="loading-indicator" style="display: none;">
	<br>
	<span class="error-box" id="error-box" style="display: none; margin-top: 1em;"></span>
</form>
<p class="login-footer">Wenn du noch kein Konto hast kannst du dich <a href="signup.php" class="button">hier registrieren ❯</a></p>
<p class="login-footer">Durch die Anmeldung wird ein Cookie gespeichert. Mehr Informationen findest du unter <a href="privacy.php">Datenschutz</a>.</p>

<script src="app/client/presentation/LoginController.js"></script>