<h1>Datenschutz</h1>

<h2>Benutzerdaten</h2>
<p>Die von dieser Webseite gesammelten Informationen werden nur zu Funktionsrelevanten Zwecken verwendet. Gespeichert werden diese Informationen:</p>
<ul>
	<li>E-Mail-Adresse</li>
	<li>Passwort</li>
	<li>Erstellte Informationen zu Besuchen (durch den Benutzer selbst erstellte Datensätze)</li>
</ul>
<p>Es werden keine Daten an Dritte weitergegeben.</p>

<h2>Cookies</h2>
<p>Diese Webseite benötigt Cookies, um die Funktionalität zur Anmeldung zur Verfügung stellen zu können. Es wird nur ein einziges Cookie im Browser des Benutzers gespeichert, nämlich das folgende:</p>
<table>
	<tr>
		<th>Cookie</th>
		<th>Beschreibung</th>
		<th>Einstufung</th>
	</tr>
	<tr>
		<td>PHPSESSID</td>
		<td>Die Sitzungs-ID, mit der der Benutzer identifiziert wird. Nur so kann gewährleistet werden, dass der Benutzer nicht bei jeder Aktion die Anmeldedaten eingeben muss.</td>
		<td>Funktionsrelevant</td>
	</tr>
</table>

<h2>Tracking</h2>
<p>Es wird kein Tracking in irgend einer Form betrieben. Es werden keine Daten zu Werbezwecken oder dergleichen gesammelt oder weitergegeben.</p>